blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://github.com/pashioya/marnix13#readme
    about: For project documentation and setup instructions.
  - name: Security Issues
    url: https://github.com/pashioya/marnix13/security/advisories/new
    about: Please report security vulnerabilities privately here.
  - name: Discussions
    url: https://github.com/pashioya/marnix13/discussions
    about: For general questions, ideas, and community discussions.